#!/usr/bin/env bash
sudo apt update
sudo apt upgrade -y
sudo apt install neofetch ncdu python3 python3-pip curl \
openjdk-8-jre-headless openjdk-11-jre-headless openjdk-17-jre-headless git gh wireguard tmux --no-install-recommends

# Install NVM and install the latest node version
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install --lts

npm install -g pnpm

# restore configs
#~/scripts/startrestore.sh

# Finished!
echo "Finished!"
