#!/usr/bin/env bash
sudo apt update
sudo apt upgrade -y
sudo apt install neofetch ncdu python3 python3-pip nodejs npm curl \
openjdk-8-jre openjdk-11-jre openjdk-17-jre steam-installer gparted \
wine-stable winetricks git wireguard font-manager tmux yubikey-manager

# Install NVM and install the latest node version
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

nvm install --lts

# Download and install Discord - credits to Cynthia (c7.pm) and Ari (adryd.com)
mkdir -p ~/.local/share/
cd ~/.local/share/
wget "https://discordapp.com/api/download/canary?platform=linux&format=tar.gz" -O DiscordCanary.tar.gz
tar -xf DiscordCanary.tar.gz
rm DiscordCanary.tar.gz

# optional if you use desktop files
mkdir -p applications
sed -i "s|/usr/share/discord-canary|$(echo $HOME)/.local/share/DiscordCanary|" DiscordCanary/discord-canary.desktop
mv DiscordCanary/discord-canary.desktop applications
mkdir -p "${HOME}/.local/share/icons/hicolor/256x256"
cp -f "DiscordCanary/discord.png" "${HOME}/.local/share/icons/hicolor/256x256/discord-canary.png"
sed -i "s|Icon=discord-canary|Icon=${HOME}/.local/share/icons/hicolor/256x256/discord-canary.png|" "${HOME}/.local/share/icons/hicolor/256x256/discord-canary.png"

# patch discord with custom client
./patchdiscord
